extends Control

# OMNI Framework - Godot Dialogue UI
# Binds the dynamic text generated by the MoE Ensemble to the game's UI CanvasLayer.

onready var dialogue_label = $Panel/RichTextLabel
onready var npc_agent = $OmniMoENPCAgent

func _ready():
    # Connect to the NPC Agent's signal (assuming we added one in the previous file)
    print("OMNI Godot: Dialogue UI initialized.")
    # npc_agent.connect("dialogue_generated", self, "_on_dialogue_received")

func display_dialogue(text: String):
    dialogue_label.bbcode_text = text
    dialogue_label.visible_characters = 0
    $Tween.interpolate_property(dialogue_label, "visible_characters", 0, text.length(), text.length() * 0.05, Tween.TRANS_LINEAR, Tween.EASE_IN_OUT)
    $Tween.start()

func _on_dialogue_received(text: String):
    display_dialogue(text)
