[package]
name = "omni-module-094"
version = "2.1.94"
authors = ["Omni Nexus <bot@nexus.dev>"]
description = "Auto-Downloaded Standard Library Component"
tier = "free"

[permissions]
allow_thread = true
