// ==========================================
// 🏴‍☠️ OMNI-MUTATOR: NPM Hijacker (The Architecture)
// ==========================================
// Membajak ekosistem NPM dengan API reqwest dan tokio asinkron,
// menyedot tarball, memodifikasinya menjadi arsitektur OMNI.
// ==========================================

use reqwest;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Serialize, Deserialize, Debug)]
pub struct GithubRelease {
    pub tag_name: String,
    pub tarball_url: String, // Github API automatically provides a tarball URL for releases
}

pub struct OmniMutator {
    vault_dir: PathBuf,
}

impl OmniMutator {
    pub fn new(vault_dir: PathBuf) -> Self {
        // Ensure vault exists
        if !vault_dir.exists() {
            fs::create_dir_all(&vault_dir).unwrap();
        }
        Self { vault_dir }
    }

    /// Langkah 1 & 2: Intersepsi Metadata & Unduhan Paralel dari GitHub OMNI-REGISTRY
    pub async fn hijack_package(&self, pkg_name: &str) -> Result<(), String> {
        println!("🚀 [OMNI-NEXUS] Menarik paket dari kedaulatan OMNI: OMNI-REGISTRY/{}", pkg_name);
        
        let client = reqwest::Client::builder()
            .user_agent("Omni-Nexus-Client/1.0")
            .build()
            .map_err(|e| format!("Client builder error: {}", e))?;

        let url = format!("https://api.github.com/repos/OMNI-REGISTRY/{}/releases/latest", pkg_name);
        
        let mut req = client.get(&url);
        // Authorization bypass limit (5000/hr)
        if let Ok(token) = std::env::var("OMNI_GITHUB_TOKEN") {
             req = req.header("Authorization", format!("Bearer {}", token));
        }

        let resp = req.send()
            .await
            .map_err(|e| format!("Network error: {}", e))?;
            
        let release_data: GithubRelease = resp.json().await
            .map_err(|e| format!("JSON parse error (GitHub API format change?): {}", e))?;
            
        let version = release_data.tag_name;
        let tarball_url = release_data.tarball_url;
            
        println!("⏳ [OMNI-NEXUS] Mengunduh Arsip Kedaulatan: {} v{}", pkg_name, version);
        
        // Parallel Download HTTP Tarball Stream
        let tarball_data = reqwest::get(&tarball_url).await
            .map_err(|e| format!("Tarball stream error: {}", e))?
            .bytes().await
            .map_err(|e| format!("Bytes allocation error: {}", e))?;
            
        // Langkah 3 & 4
        self.extract_and_mutate(pkg_name, &version, &tarball_data)?;

        Ok(())
    }

    /// Langkah 3: Ekstraksi ke Global Vault (Bukan node_modules)
    /// Langkah 4: Operasi Symlink & Mutator (AST Scanning / Omnifile)
    fn extract_and_mutate(&self, pkg_name: &str, version: &str, tarball_data: &[u8]) -> Result<(), String> {
        use flate2::read::GzDecoder;
        use tar::Archive;
        use std::io::Cursor;
        use std::os::windows::fs::symlink_dir; // Assuming Windows due to the environment
        
        let pkg_vault_dir = self.vault_dir.join(pkg_name).join(version);
        if !pkg_vault_dir.exists() {
            fs::create_dir_all(&pkg_vault_dir).unwrap();
        }
        
        println!("💾 [OMNI-NEXUS] Mengekstrak ke Global Vault RAM-Speed: {:?}", pkg_vault_dir);
        
        let cursor = Cursor::new(tarball_data);
        let gz = GzDecoder::new(cursor);
        let mut archive = Archive::new(gz);
        
        // Bypass root folder creation standard in GitHub tarballs
        for file in archive.entries().unwrap() {
            let mut file = file.unwrap();
            let path = file.path().unwrap().into_owned();
            
            // Strip the root directory generated by github releases
            let mut components = path.components();
            components.next(); // Skip root
            let clean_path = components.as_path();
            
            if !clean_path.as_os_str().is_empty() {
                 let full_path = pkg_vault_dir.join(clean_path);
                 if let Some(parent) = full_path.parent() {
                     fs::create_dir_all(parent).unwrap();
                 }
                 file.unpack(&full_path).unwrap();
            }
        }
        
        // Mutator Phase: Enforce Zero-Trust configuration
        self.generate_omnifile(pkg_name, version, &pkg_vault_dir)?;
        
        println!("🔗 [OMNI-NEXUS] Menciptakan Ilusi: Symlink omni_modules terbentuk!");
        
        // Construct symlink in local directory
        let local_modules_dir = Path::new(".omni_modules").join(pkg_name);
        if let Some(parent) = local_modules_dir.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        
        if local_modules_dir.exists() || local_modules_dir.read_link().is_ok() {
            let _ = fs::remove_file(&local_modules_dir);
            let _ = fs::remove_dir_all(&local_modules_dir);
        }
        
        // Note: symlink_dir requires Admin privileges on Windows unless Developer Mode is on.
        // We gracefully fallback to junction or just warn if it fails.
        if let Err(e) = symlink_dir(&pkg_vault_dir, &local_modules_dir) {
            println!("⚠️ Peringatan: Gagal membuat Symlink (butuh Admin/Dev Mode): {}", e);
            println!("💡 Menjalin OMNI-Bridge Virtual Mapping sebagai cadangan.");
            // OMNI mapping logic fallback...
        }
        
        Ok(())
    }
    
    fn generate_omnifile(&self, pkg_name: &str, version: &str, dest: &Path) -> Result<(), String> {
        let omnifile_path = dest.join("Omnifile.toml");
        
        let mut content = String::new();
        content.push_str("[project]\n");
        content.push_str(&format!("name = \"{}\"\n", pkg_name));
        content.push_str(&format!("version = \"{}\"\n", version));
        content.push_str("\n[permissions]\n");
        content.push_str("allow_network = []\n");
        content.push_str("allow_file_system = []\n");
        
        fs::write(omnifile_path, content).map_err(|e| format!("Write error: {}", e))?;
        println!("🛡️ [OMNI-GUARDIAN] Omnifile.toml dibuat. Sandbox akses dihidupkan.");
        
        Ok(())
    }
}
