# OMNI AIDER: Diff Parser
# Ruby domain logic for parsing standard unified diffs generated by LLMs 
# and applying them safely to the local syntax tree.
# Source: paul-gauthier/aider

module Omni
  module Aider
    class DiffParser
      class ParseError < StandardError; end

      # Parses a unified diff string into a structured patch object
      def self.parse(diff_string)
        raise ParseError, "Diff string is empty" if diff_string.nil? || diff_string.strip.empty?

        patches = []
        current_patch = nil

        diff_string.each_line do |line|
          line = line.chomp

          if line.start_with?('--- ')
            current_patch = { old_file: line[4..-1], new_file: nil, hunks: [] }
          elsif line.start_with?('+++ ')
            raise ParseError, "Malformed diff: +++ without ---" unless current_patch
            current_patch[:new_file] = line[4..-1]
            patches << current_patch
          elsif line.start_with?('@@ ')
            raise ParseError, "Malformed diff: @@ without file header" unless current_patch
            # Parse chunk header: @@ -start,count +start,count @@
            match = line.match(/@@ -(\d+),?(\d*) \+(\d+),?(\d*) @@/)
            if match
              current_patch[:hunks] << {
                old_start: match[1].to_i,
                old_lines: match[2].empty? ? 1 : match[2].to_i,
                new_start: match[3].to_i,
                new_lines: match[4].empty? ? 1 : match[4].to_i,
                changes: []
              }
            end
          else
            next unless current_patch && !current_patch[:hunks].empty?
            # Add line changes to the latest hunk
            if line.start_with?('+') || line.start_with?('-') || line.start_with?(' ')
              current_patch[:hunks].last[:changes] << line
            end
          end
        end

        patches
      rescue StandardError => e
        raise ParseError, "Failed to parse diff: #{e.message}"
      end
    end
  end
end
