#!/bin/bash
# ==========================================
# 🖥️ OMNI FRAMEWORK — VPS Deploy Script
# Generated by: omni deploy vps
# ==========================================
# Penggunaan: ./deploy-vps.sh <IP_SERVER> <USER>
# Contoh:     ./deploy-vps.sh 167.99.88.123 root
# ==========================================

SERVER_IP=${1:-"YOUR_SERVER_IP"}
SERVER_USER=${2:-"root"}
DEPLOY_DIR="/var/www/omni-app"

echo "🚀 [OMNI-DEPLOY] Mengirim ke VPS: ${SERVER_USER}@${SERVER_IP}"
echo "📂 Target: ${DEPLOY_DIR}"
echo ""

# 1. Buat direktori di server
ssh ${SERVER_USER}@${SERVER_IP} "mkdir -p ${DEPLOY_DIR}/release/public"

# 2. Upload binary + static files
echo "📤 Mengunggah biner..."
scp release/bin/omni_gateway ${SERVER_USER}@${SERVER_IP}:${DEPLOY_DIR}/omni_gateway

echo "📤 Mengunggah frontend..."
scp -r release/public/* ${SERVER_USER}@${SERVER_IP}:${DEPLOY_DIR}/release/public/

# 3. Set permissions & restart service
ssh ${SERVER_USER}@${SERVER_IP} << 'ENDSSH'
chmod +x /var/www/omni-app/omni_gateway
systemctl restart omni-framework 2>/dev/null || echo "⚠️ Systemd service belum dibuat. Jalankan: omni make service"
echo "✅ Deploy selesai!"
ENDSSH

echo ""
echo "🌐 App online di: http://${SERVER_IP}:3000"
