# ==========================================
# 🐳 OMNI FRAMEWORK — Multi-Stage Docker Build
# Generated by: omni deploy docker
# ==========================================

# Stage 1: Build Frontend (Vite SSG)
FROM node:20-alpine AS frontend-builder
WORKDIR /app/ui
COPY ui/package*.json ./
RUN npm ci --production=false
COPY ui/ .
RUN npm run build

# Stage 2: Build Backend (Golang Bare-Metal)
FROM golang:1.22-alpine AS backend-builder
WORKDIR /app/api
COPY api/go.* ./
RUN go mod download
COPY api/ .
# CGO_ENABLED=0 → Biner 100% mandiri, tanpa dependency C library
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o omni_gateway main.go

# Stage 3: Production (Alpine Minimal ~5MB base)
FROM alpine:3.19
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/

# Salin artefak yang sudah dikompilasi
COPY --from=backend-builder /app/api/omni_gateway .
COPY --from=frontend-builder /app/ui/dist ./release/public

# Health check bawaan
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s \
  CMD wget -qO- http://localhost:3000/api/v1/health || exit 1

EXPOSE 3000

# Timezone default (bisa di-override via ENV)
ENV TZ=Asia/Jakarta

CMD ["./omni_gateway"]
