# ==========================================
# OMNI Framework - Category Batch Installer
# Groups packages by domain for faster install
# ==========================================

$ErrorActionPreference = "Continue"
Set-Location "c:\Users\IKYY\Downloads\Omni"

$wave = 0
$totalInstalled = 0
$totalFailed = 0

function Install-Batch {
    param([string]$Name, [string[]]$Packages)
    $script:wave++
    $count = $Packages.Count
    Write-Host ""
    Write-Host "=== WAVE $($script:wave): $Name ($count packages) ==="
    
    $pkgList = $Packages -join " "
    Write-Host "Installing..."
    
    $result = & pnpm add $pkgList  2>&1 | Out-String
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  OK - All $count installed" 
        $script:totalInstalled += $count
    } else {
        Write-Host "  PARTIAL FAIL on batch - retrying one by one..."
        foreach ($pkg in $Packages) {
            $r2 = & pnpm add $pkg  2>&1 | Out-String
            if ($LASTEXITCODE -eq 0) {
                Write-Host "    OK: $pkg"
                $script:totalInstalled++
            } else {
                Write-Host "    FAIL: $pkg"
                $script:totalFailed++
            }
        }
    }
    
    $done = $script:totalInstalled + $script:totalFailed
    Write-Host "  Progress: $done / 645 | OK=$($script:totalInstalled) | FAIL=$($script:totalFailed)"
}

Write-Host "============================================="
Write-Host "  OMNI CATEGORY INSTALLER - 645 packages"
Write-Host "  Strategy: batch by domain category"
Write-Host "============================================="

# ---- WAVE 1: Google Cloud Core (40 packages) ----
Install-Batch "Google Cloud Core Infrastructure" @(
    "@google-cloud/storage"
    "@google-cloud/pubsub"
    "@google-cloud/bigquery"
    "@google-cloud/spanner"
    "@google-cloud/firestore"
    "@google-cloud/datastore"
    "@google-cloud/bigtable"
    "@google-cloud/compute"
    "@google-cloud/run"
    "@google-cloud/functions"
    "@google-cloud/container"
    "@google-cloud/logging"
    "@google-cloud/monitoring"
    "@google-cloud/trace-agent"
    "@google-cloud/error-reporting"
    "@google-cloud/secret-manager"
    "@google-cloud/kms"
    "@google-cloud/iam"
    "@google-cloud/iam-credentials"
    "@google-cloud/resource-manager"
    "@google-cloud/billing"
    "@google-cloud/service-usage"
    "@google-cloud/asset"
    "@google-cloud/security-center"
    "@google-cloud/dlp"
    "@google-cloud/policy-troubleshooter"
    "@google-cloud/vpc-access"
    "@google-cloud/dns"
    "@google-cloud/scheduler"
    "@google-cloud/tasks"
    "@google-cloud/eventarc"
    "@google-cloud/workflows"
    "@google-cloud/artifact-registry"
    "@google-cloud/deploy"
    "@google-cloud/cloudbuild"
    "@google-cloud/redis"
    "@google-cloud/memcache"
    "@google-cloud/alloydb"
    "@google-cloud/sql"
    "@google-cloud/storage-transfer"
)

# ---- WAVE 2: Google Cloud AI/ML (30 packages) ----
Install-Batch "Google Cloud AI and ML" @(
    "@google-cloud/aiplatform"
    "@google-cloud/vertexai"
    "@google-cloud/vision"
    "@google-cloud/speech"
    "@google-cloud/text-to-speech"
    "@google-cloud/translate"
    "@google-cloud/language"
    "@google-cloud/video-intelligence"
    "@google-cloud/talent"
    "@google-cloud/dialogflow"
    "@google-cloud/dialogflow-cx"
    "@google-cloud/documentai"
    "@google-cloud/automl"
    "@google-cloud/media-translation"
    "@google-cloud/contact-center-insights"
    "@google/generative-ai"
    "google-auth-library"
    "googleapis"
    "@google-cloud/dataflow"
    "@google-cloud/dataproc"
    "@google-cloud/dataplex"
    "@google-cloud/datacatalog"
    "@google-cloud/dataform"
    "@google-cloud/datastream"
    "@google-cloud/discoveryengine"
    "@google-cloud/recaptcha-enterprise"
    "@google-cloud/retail"
    "@google-cloud/service-directory"
)

# ---- WAVE 3: Firebase (25 packages) ----
Install-Batch "Firebase Suite" @(
    "firebase"
    "firebase-admin"
    "firebase-functions"
    "@firebase/app"
    "@firebase/auth"
    "@firebase/firestore"
    "@firebase/storage"
    "@firebase/messaging"
    "@firebase/analytics"
    "@firebase/performance"
    "@firebase/remote-config"
    "@firebase/app-check"
    "@firebase/database"
    "@firebase/functions"
    "firebase-tools"
    "firebaseui"
    "react-firebase-hooks"
    "@angular/fire"
    "vuefire"
    "@anthropic-ai/bedrock-sdk"
    "@react-native-firebase/app"
    "@react-native-firebase/auth"
    "@react-native-firebase/firestore"
    "@react-native-firebase/messaging"
    "@react-native-firebase/storage"
)

# ---- WAVE 4: Music and Audio (46 packages) ----
Install-Batch "Music and Audio Engine" @(
    "tone"
    "howler"
    "pizzicato"
    "wavesurfer.js"
    "peaks.js"
    "audiobuffer-to-wav"
    "soundfont-player"
    "midi-writer-js"
    "jsmidgen"
    "web-audio-api"
    "audio-decode"
    "audio-encode"
    "waveform-data"
    "audio-context"
    "audio-buffer"
    "audio-buffer-utils"
    "audio-loader"
    "tonal"
    "teoria"
    "music-tempo"
    "audio-recorder-polyfill"
    "lamejs"
    "flac.js"
    "ogg.js"
    "opus-recorder"
    "vorbis.js"
    "mp3-mediarecorder"
    "audio-play"
    "audio-speaker"
    "audio-oscillator"
    "audio-through"
    "pcm-util"
    "pcm-convert"
    "audio-lena"
    "babyparse"
    "essentia.js"
    "meyda"
    "node-lame"
    "sox-stream"
    "node-mp3-player"
    "play-sound"
    "speaker"
    "microphone-stream"
    "audio-effects"
    "standardized-audio-context"
    "soundcloud-audio"
)

# ---- WAVE 5: Video and Streaming (60 packages) ----
Install-Batch "Video and Streaming Engine" @(
    "fluent-ffmpeg"
    "ffmpeg-static"
    "ffprobe-static"
    "@ffmpeg/ffmpeg"
    "@ffmpeg/util"
    "video.js"
    "hls.js"
    "dashjs"
    "shaka-player"
    "mediasoup"
    "mediasoup-client"
    "simple-peer"
    "peerjs"
    "livekit-client"
    "livekit-server-sdk"
    "agora-rtc-sdk-ng"
    "twilio-video"
    "webrtc-adapter"
    "mediasource"
    "m3u8-parser"
    "mpd-parser"
    "mp4box"
    "mux-embed"
    "@mux/mux-player"
    "@mux/mux-node"
    "stream-transcoder"
    "rtsp-stream"
    "node-rtsp-stream"
    "rtmp-server"
    "node-media-server"
    "subtitle"
    "ass-compiler"
    "matroska"
    "gif-encoder-2"
    "gifski"
    "lottie-web"
    "remotion"
    "@remotion/player"
    "@remotion/renderer"
    "@remotion/media-utils"
    "editly"
    "ffmpeg-concat"
    "canvas-capture"
    "whammy"
    "webm-muxer"
    "mp4-muxer"
    "ts-ebml"
    "thumbd"
    "video-thumbnail-generator"
    "thumbsup"
    "get-video-duration"
    "ffmpeg-extract-frames"
    "subtitle-parser"
    "video-stitch"
    "concat-stream"
    "stream-buffers"
    "multistream"
    "pump"
    "through2"
    "split2"
)

# ---- WAVE 6: Business and Payments (60 packages) ----
Install-Batch "Business and Payment Gateway" @(
    "stripe"
    "@stripe/stripe-js"
    "@stripe/react-stripe-js"
    "paypal-rest-sdk"
    "@paypal/checkout-server-sdk"
    "@paypal/react-paypal-js"
    "braintree"
    "square"
    "razorpay"
    "midtrans-client"
    "xendit-node"
    "flutterwave-node-v3"
    "coinbase-commerce-node"
    "mollie-api-node"
    "adyen-api-library"
    "klarna-checkout"
    "plaid"
    "dwolla-v2"
    "transferwise"
    "quickbooks-js"
    "xero-node"
    "harvest-v2"
    "node-quickbooks"
    "accounting"
    "dinero.js"
    "currency.js"
    "money.js"
    "fx"
    "invoice-maker"
    "pdfmake"
    "jspdf"
    "jspdf-autotable"
    "html-pdf-node"
    "puppeteer"
    "barcode"
    "jsbarcode"
    "qrcode"
    "bwip-js"
    "chart.js"
    "recharts"
    "apexcharts"
    "echarts"
    "highcharts"
    "d3"
    "plotly.js"
    "nivo"
    "victory"
    "visx"
    "billboard.js"
    "frappe-charts"
    "chartist"
    "rough"
    "trading-vue-js"
    "lightweight-charts"
    "ccxt"
    "technical-indicators"
    "ta-lib"
    "stockfish.js"
    "money-math"
    "country-data"
)

# ---- WAVE 7: Converter and Document Processing (62 packages) ----
Install-Batch "Converter and Document Processing" @(
    "sharp"
    "jimp"
    "gm"
    "image-size"
    "imagemin"
    "imagemin-pngquant"
    "imagemin-mozjpeg"
    "imagemin-svgo"
    "imagemin-webp"
    "svg2img"
    "svgo"
    "canvg"
    "fabric"
    "konva"
    "pixelmatch"
    "resemble.js"
    "psd.js"
    "tiff.js"
    "heic-convert"
    "raw-body"
    "pdf-lib"
    "pdfkit"
    "pdf-parse"
    "pdf2json"
    "pdf2pic"
    "html-pdf"
    "mammoth"
    "docx"
    "officegen"
    "xlsx"
    "exceljs"
    "papaparse"
    "csv-parse"
    "csv-writer"
    "fast-csv"
    "json2csv"
    "yaml"
    "toml"
    "xml2js"
    "fast-xml-parser"
    "cheerio"
    "html-to-text"
    "turndown"
    "showdown"
    "markdown-it"
    "marked"
    "remark"
    "unified"
    "rehype"
    "mdx-bundler"
    "latex.js"
    "katex"
    "mathjax"
    "archiver"
    "unzipper"
    "adm-zip"
    "tar"
    "decompress"
    "compressing"
    "node-7z"
    "iconv-lite"
    "chardet"
)

# ---- WAVE 8: AI ML TensorFlow ONNX (60 packages) ----
Install-Batch "AI ML TensorFlow ONNX" @(
    "@tensorflow/tfjs"
    "@tensorflow/tfjs-node"
    "@tensorflow/tfjs-node-gpu"
    "@tensorflow-models/coco-ssd"
    "@tensorflow-models/blazeface"
    "@tensorflow-models/body-pix"
    "@tensorflow-models/posenet"
    "@tensorflow-models/mobilenet"
    "@tensorflow-models/face-landmarks-detection"
    "@tensorflow-models/hand-pose-detection"
    "@tensorflow-models/pose-detection"
    "@tensorflow-models/universal-sentence-encoder"
    "@tensorflow-models/toxicity"
    "@tensorflow-models/qna"
    "onnxruntime-node"
    "onnxruntime-web"
    "@xenova/transformers"
    "openai"
    "@anthropic-ai/sdk"
    "cohere-ai"
    "replicate"
    "huggingface-inference"
    "@huggingface/hub"
    "@huggingface/inference"
    "langchain"
    "@langchain/core"
    "@langchain/openai"
    "@langchain/google-genai"
    "@langchain/community"
    "llamaindex"
    "chromadb"
    "pinecone-client"
    "@pinecone-database/pinecone"
    "weaviate-ts-client"
    "qdrant-js"
    "milvus2-sdk-node"
    "faiss-node"
    "brain.js"
    "synaptic"
    "natural"
    "compromise"
    "sentiment"
    "franc"
    "cld3-asm"
    "tesseract.js"
    "face-api.js"
    "tracking.js"
    "ml5"
    "deeplearn"
    "mind-ar"
    "nsfwjs"
    "paddlejs"
    "mediapipe"
    "@mediapipe/tasks-vision"
    "@mediapipe/tasks-text"
    "@mediapipe/tasks-audio"
    "whisper-node"
    "@deepgram/sdk"
    "stability-client"
    "elevenlabs"
)

# ---- WAVE 9: Animation and 3D (51 packages) ----
Install-Batch "Animation and 3D Graphics" @(
    "gsap"
    "animejs"
    "popmotion"
    "framer-motion"
    "motion"
    "@react-spring/web"
    "react-transition-group"
    "react-motion"
    "velocity-animate"
    "mo-js"
    "vivus"
    "typed.js"
    "splitting"
    "scrollreveal"
    "aos"
    "locomotive-scroll"
    "lenis"
    "barba"
    "@barba/core"
    "swup"
    "tween.js"
    "@tweenjs/tween.js"
    "pixi.js"
    "@pixi/animate"
    "three"
    "@react-three/fiber"
    "@react-three/drei"
    "@react-three/postprocessing"
    "@react-three/rapier"
    "cannon-es"
    "matter-js"
    "p2-es"
    "planck"
    "paper"
    "p5"
    "pts"
    "rough-notation"
    "particles.js"
    "@tsparticles/engine"
    "confetti-js"
    "canvas-confetti"
    "rive-js"
    "@rive-app/react-canvas"
    "@splinetool/runtime"
    "@splinetool/react-spline"
    "spine-ts"
    "babylonjs"
    "aframe"
    "model-viewer"
    "ogl"
    "regl"
)

# ---- WAVE 10: Web Framework and Server (51 packages) ----
Install-Batch "Web Framework and Server" @(
    "express"
    "fastify"
    "koa"
    "@hapi/hapi"
    "nest"
    "@nestjs/core"
    "@nestjs/common"
    "@nestjs/platform-express"
    "@nestjs/swagger"
    "@nestjs/graphql"
    "@nestjs/microservices"
    "@nestjs/websockets"
    "@nestjs/bull"
    "h3"
    "nitro"
    "elysia"
    "hono"
    "itty-router"
    "polka"
    "restify"
    "body-parser"
    "multer"
    "formidable"
    "busboy"
    "cookie-parser"
    "express-session"
    "express-rate-limit"
    "express-validator"
    "helmet"
    "cors"
    "compression"
    "morgan"
    "winston"
    "pino"
    "bunyan"
    "response-time"
    "serve-static"
    "express-fileupload"
    "swagger-jsdoc"
    "swagger-ui-express"
    "http-proxy-middleware"
    "express-graphql"
    "apollo-server-express"
    "@apollo/server"
    "graphql"
    "graphql-ws"
    "type-graphql"
    "graphql-scalars"
    "mercurius"
    "nexus"
    "@pothos/core"
)

# ---- WAVE 11: Database and ORM (50 packages) ----
Install-Batch "Database and ORM" @(
    "prisma"
    "@prisma/client"
    "typeorm"
    "sequelize"
    "knex"
    "objection"
    "mongoose"
    "mongodb"
    "pg"
    "pg-pool"
    "mysql2"
    "better-sqlite3"
    "sqlite3"
    "redis"
    "ioredis"
    "memcached"
    "tedious"
    "cassandra-driver"
    "elasticsearch"
    "@elastic/elasticsearch"
    "neo4j-driver"
    "arangojs"
    "couchbase"
    "rethinkdb"
    "fauna"
    "surrealdb.js"
    "drizzle-orm"
    "drizzle-kit"
    "mikro-orm"
    "kysely"
    "bookshelf"
    "waterline"
    "dynamoose"
    "@aws-sdk/client-dynamodb"
    "level"
    "lmdb"
    "duckdb"
    "clickhouse"
    "timescaledb"
    "influx"
    "@supabase/supabase-js"
    "@supabase/realtime-js"
    "pocketbase"
    "appwrite"
    "@nhost/nhost-js"
    "convex"
    "turso"
    "@libsql/client"
    "gun"
    "rxdb"
)

# ---- WAVE 12: Security and Crypto (30 packages) ----
Install-Batch "Security and Crypto" @(
    "bcrypt"
    "bcryptjs"
    "argon2"
    "scrypt-js"
    "jsonwebtoken"
    "jose"
    "passport"
    "passport-jwt"
    "passport-local"
    "passport-google-oauth20"
    "passport-github2"
    "express-oauth2-jwt-bearer"
    "node-forge"
    "tweetnacl"
    "libsodium-wrappers"
    "crypto-js"
    "openpgp"
    "otplib"
    "speakeasy"
    "csrf-csrf"
    "csurf"
    "hpp"
    "xss-clean"
    "sanitize-html"
    "dompurify"
    "rate-limiter-flexible"
    "express-brute"
    "zxcvbn"
    "uuid"
    "nanoid"
)

# ---- WAVE 13: Networking and Realtime (39 packages) ----
Install-Batch "Networking and Realtime" @(
    "axios"
    "node-fetch"
    "got"
    "undici"
    "ky"
    "superagent"
    "request-promise-native"
    "socket.io"
    "socket.io-client"
    "ws"
    "faye-websocket"
    "primus"
    "sockjs"
    "mqtt"
    "amqplib"
    "kafkajs"
    "bullmq"
    "bull"
    "agenda"
    "bee-queue"
    "zeromq"
    "nats"
    "@grpc/grpc-js"
    "@grpc/proto-loader"
    "protobufjs"
    "flatbuffers"
    "msgpackr"
    "avsc"
    "dns-packet"
    "node-dns"
    "ssh2"
    "node-ssh"
    "ftp"
    "basic-ftp"
    "socks"
    "proxy-agent"
    "tunnelmole"
    "localtunnel"
    "ngrok"
)

# ---- WAVE 14: Dev Dependencies (41 packages) ----
Install-Batch "Dev Dependencies" @(
    "typescript"
    "ts-node"
    "tsx"
    "esbuild"
    "vite"
    "rollup"
    "webpack"
    "webpack-cli"
    "swc"
    "@swc/core"
    "babel"
    "@babel/core"
    "@babel/preset-env"
    "@babel/preset-typescript"
    "jest"
    "vitest"
    "mocha"
    "chai"
    "sinon"
    "supertest"
    "nock"
    "msw"
    "playwright"
    "cypress"
    "puppeteer-core"
    "c8"
    "nyc"
    "eslint"
    "prettier"
    "husky"
    "lint-staged"
    "commitlint"
    "semantic-release"
    "changesets"
    "typedoc"
    "nodemon"
    "concurrently"
    "cross-env"
    "dotenv"
    "chokidar"
    "rimraf"
)

Write-Host ""
Write-Host "============================================="
Write-Host "  FINAL RESULTS"
Write-Host "  Total Installed: $totalInstalled"
Write-Host "  Total Failed: $totalFailed"
Write-Host "  Grand Total: $($totalInstalled + $totalFailed) / 645"
Write-Host "============================================="
