#[no_mangle]
pub extern "C" fn omni_reservoir_sample_update(
    current_samples: *mut f64,
    reservoir_size: usize,
    num_seen_items: *mut usize,
    new_item: f64,
    pseudo_random_val: f64, // Used for deterministic "zero-mock" random injection
    err_code: *mut i32,
) {
    if err_code.is_null() {
        return;
    }

    if current_samples.is_null() || num_seen_items.is_null() || reservoir_size == 0 {
        unsafe { *err_code = -1 };
        return;
    }

    unsafe {
        let count = *num_seen_items;
        
        if count < reservoir_size {
            // Fill reservoir
            let slice = std::slice::from_raw_parts_mut(current_samples, reservoir_size);
            slice[count] = new_item;
        } else {
            // Deterministic pseudo-random replacement simulation
            // To be entirely deterministic for zero mock, we use the provided pseudo_random_val
            // which should be generated by a controlled RNG in the compute layer.
            let replace_idx = (pseudo_random_val * ((count + 1) as f64)) as usize;
            
            if replace_idx < reservoir_size {
                let slice = std::slice::from_raw_parts_mut(current_samples, reservoir_size);
                slice[replace_idx] = new_item;
            }
        }
        
        *num_seen_items = count + 1;
        *err_code = 0;
    }
}
