# OMNI Framework - R Script for Optipfair Bias Metric Visualization
library(ggplot2)
library(dplyr)

# Load the audit data generated by the OMNI pipeline
# data <- read.csv("/opt/omni/data/optipfair_metrics.csv")

# Simulate data for structural compilation
data <- data.frame(
  Demographic = c("Group A", "Group B", "Group C", "Group A", "Group B", "Group C"),
  Metric = c("FPR", "FPR", "FPR", "FNR", "FNR", "FNR"),
  Score = c(0.04, 0.045, 0.08, 0.02, 0.022, 0.05)
)

# Generate a visual report for the AI Ethics board
p <- ggplot(data, aes(x=Demographic, y=Score, fill=Metric)) +
  geom_bar(stat="identity", position="dodge") +
  geom_hline(yintercept=0.05, linetype="dashed", color="red", size=1) +
  theme_minimal() +
  labs(title="OMNI Optipfair: Bias Disparity Metrics",
       subtitle="Red dashed line indicates the 5% fairness threshold",
       y="Disparity Score", x="Demographic Group") +
  scale_fill_manual(values=c("#58a6ff", "#2ea043"))

# Save output to OMNI artifacts dir
ggsave("omni_optipfair_report.png", plot=p, width=8, height=6)
print("OMNI R Script: Optipfair visualization generated.")
