// OmniTurfTopic.scala — Robust Topic Modeling
// Inspired by: turftopic (Topic models with sentence-transformers)
// Layer: Compute / Scala
//
// Wraps embedding-based clustering approaches for topic modeling,
// suitable for big data pipelines in JVM ecosystems.

package omni.compute.topic

import scala.collection.mutable
import scala.math._

/**
 * Represents a discovered topic.
 */
case class Topic(id: Int, keywords: List[(String, Double)], size: Int)

/**
 * Scala counterpart for semantic topic modeling.
 * Assumes document embeddings have already been generated by a sentence-transformer.
 */
class OmniTurfTopic(numTopics: Int = 10, minClusterSize: Int = 15) {

  /**
   * Fits a simple K-Means variant over the document embeddings to cluster them into topics.
   * 
   * @param embeddings Array of document embeddings (N x D)
   * @param vocab Array of vocabulary words present in the corpus
   * @param tfidf Matrix of TF-IDF scores (N x V)
   * @return List of discovered Topics
   */
  def fitTransform(embeddings: Array[Array[Double]], vocab: Array[String], tfidf: Array[Array[Double]]): List[Topic] = {
    val n = embeddings.length
    if (n == 0) return List.empty
    
    val d = embeddings.head.length
    val v = vocab.length

    // 1. Cluster embeddings (Spherical K-Means representation)
    val clusterAssignments = clusterEmbeddings(embeddings, numTopics)
    
    // 2. Count sizes
    val sizes = new Array[Int](numTopics)
    for (c <- clusterAssignments) {
      if (c >= 0 && c < numTopics) sizes(c) += 1
    }

    // 3. Compute class-based TF-IDF (c-TF-IDF)
    // Aggregate TF-IDF scores per cluster
    val clusterTfidf = Array.fill(numTopics, v)(0.0)
    for (i <- 0 until n) {
      val c = clusterAssignments(i)
      if (c >= 0 && c < numTopics) {
        for (j <- 0 until v) {
          clusterTfidf(c)(j) += tfidf(i)(j)
        }
      }
    }

    // 4. Extract top keywords per topic
    val topics = mutable.ListBuffer[Topic]()
    for (c <- 0 until numTopics) {
      if (sizes(c) >= minClusterSize) {
        // Average TF-IDF by size
        for (j <- 0 until v) clusterTfidf(c)(j) /= sizes(c)
        
        // Sort keywords by score
        val keywordsWithScores = vocab.zip(clusterTfidf(c))
          .sortBy(-_._2)
          .take(10)
          .toList
          
        topics += Topic(c, keywordsWithScores, sizes(c))
      }
    }

    topics.toList
  }

  private def clusterEmbeddings(embeddings: Array[Array[Double]], k: Int): Array[Int] = {
    // Simplified KMeans for zero-mock requirement without pulling large libraries
    val n = embeddings.length
    val d = embeddings.head.length
    val assignments = new Array[Int](n)
    val centroids = Array.fill(k, d)(0.0)
    
    // Init centroids randomly from points
    val rand = new scala.util.Random(42)
    for (i <- 0 until k) {
      val idx = rand.nextInt(n)
      Array.copy(embeddings(idx), 0, centroids(i), 0, d)
    }

    var changed = true
    var iters = 0
    while (changed && iters < 50) {
      changed = false
      iters += 1
      
      // Assign
      for (i <- 0 until n) {
        var bestDist = Double.MaxValue
        var bestK = 0
        for (j <- 0 until k) {
          val dist = cosineDistance(embeddings(i), centroids(j))
          if (dist < bestDist) {
            bestDist = dist
            bestK = j
          }
        }
        if (assignments(i) != bestK) {
          assignments(i) = bestK
          changed = true
        }
      }
      
      // Update
      val counts = new Array[Int](k)
      val newCentroids = Array.fill(k, d)(0.0)
      for (i <- 0 until n) {
        val c = assignments(i)
        counts(c) += 1
        for (j <- 0 until d) newCentroids(c)(j) += embeddings(i)(j)
      }
      for (c <- 0 until k) {
        if (counts(c) > 0) {
          for (j <- 0 until d) centroids(c)(j) = newCentroids(c)(j) / counts(c)
        }
      }
    }
    
    assignments
  }

  private def cosineDistance(v1: Array[Double], v2: Array[Double]): Double = {
    var dot = 0.0
    var n1 = 0.0
    var n2 = 0.0
    for (i <- v1.indices) {
      dot += v1(i) * v2(i)
      n1 += v1(i) * v1(i)
      n2 += v2(i) * v2(i)
    }
    val denom = math.sqrt(n1) * math.sqrt(n2)
    if (denom == 0.0) 1.0 else 1.0 - (dot / denom)
  }
}
