// OMNI UI & Visualization Layer
// Time Series Explainability Dashboard
// Inspired by dxgZ/awesome-time-series-explainability.
// Provides a front-end view of perturbation and saliency metrics.

import React, { useState, useEffect } from 'react';
import { OmniIpcClient } from '@omni-bridge/system/ipc';

interface TimeSeriesPoint {
    timestamp: string;
    value: number;
    saliencyScore: number;
}

interface ExplainabilityState {
    data: TimeSeriesPoint[];
    method: 'Saliency' | 'Perturbation' | 'LIME' | 'SHAP';
    loading: boolean;
}

export const OmniTSExplainabilityDashboard: React.FC = () => {
    const [state, setState] = useState<ExplainabilityState>({
        data: [],
        method: 'Saliency',
        loading: true,
    });

    useEffect(() => {
        // Fetch explainability metrics generated by the R/Python backend layers
        const fetchMetrics = async () => {
            try {
                // In production, this uses zero-copy shared memory IPC
                const response = await OmniIpcClient.request('timeseries.explain', {
                    method: state.method,
                    datasetId: 'global_temperature_anomaly_01'
                });
                
                setState(s => ({ ...s, data: response.points, loading: false }));
            } catch (error) {
                console.error("OMNI TS-Dash Error: Failed to load TS explainability metrics", error);
                setState(s => ({ ...s, loading: false }));
            }
        };

        fetchMetrics();
    }, [state.method]);

    return (
        <div className="omni-dashboard-container">
            <header className="omni-dashboard-header">
                <h2>OMNI Time Series Explainability</h2>
                <select 
                    value={state.method}
                    onChange={(e) => setState({ ...state, method: e.target.value as any, loading: true })}
                >
                    <option value="Saliency">Saliency Maps</option>
                    <option value="Perturbation">Perturbation Analysis</option>
                    <option value="LIME">TS-LIME</option>
                    <option value="SHAP">TS-SHAP</option>
                </select>
            </header>

            <div className="omni-chart-area">
                {state.loading ? (
                    <div className="omni-spinner">Loading native metrics...</div>
                ) : (
                    <div className="omni-timeseries-render">
                        {/* 
                          Render standard D3 or Recharts here.
                          Points with high `saliencyScore` are highlighted in red.
                        */}
                        <p>Rendered {state.data.length} points via Universal Binary IPC.</p>
                    </div>
                )}
            </div>
        </div>
    );
};
