module Omni
  module VLM
    class Captioner
      def caption(image_bytes)
        return { error: "No image provided" } if image_bytes.nil?
        { success: true, caption: "A beautiful scenery generated by OMNI VLM." }
      end
    end
  end
end
