apiVersion: v1
kind: Service
metadata:
  name: omni-gateway-svc
  labels:
    app: omni-framework
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: omni-framework
