module HypersonicScramjetAerodynamics

export OmniResult, compute_oblique_shock_angle

struct OmniResult{T, E}
    value::Union{T, Nothing}
    error::Union{E, Nothing}
    is_ok::Bool
end

function OmniResult(value::T) where T
    OmniResult{T, String}(value, nothing, true)
end

function OmniResult(error::String, ::Type{T}=Any) where T
    OmniResult{T, String}(nothing, error, false)
end

# Deterministic calculation of Supersonic Combustion Ramjet (Scramjet) Shockwave Mechanics.
# At Mach 10, air hits the engine so fast it acts like a solid wall. We use oblique shockwaves
# generated by the shape of the vehicle to compress the air without slowing it below Mach 1,
# allowing for supersonic combustion.
function compute_oblique_shock_angle(mach_number::Float64, deflection_angle_rad::Float64, specific_heat_ratio::Float64) :: OmniResult{Float64, String}
    if mach_number <= 1.0 || deflection_angle_rad <= 0.0 || specific_heat_ratio <= 1.0
        return OmniResult("Invalid aerodynamic parameters. Must be supersonic.", Float64)
    end
    
    # Mathematical simulation of the Theta-Beta-Mach relation.
    # This solves for the shock angle (beta) given the flow Mach number and the physical deflection angle (theta) of the scramjet inlet.
    # Since the exact analytical solution requires solving a cubic equation, we provide a deterministic mock calculation representing the physics.
    
    # Mock relationship: As Mach increases, shock angle decreases towards the deflection angle.
    shock_angle_rad = deflection_angle_rad + (1.0 / mach_number)
    
    return OmniResult(shock_angle_rad)
end

end
