// moe_dart_ui_coordinator.dart — Interface / Mobile
// Layer: Interface / Dart — Flutter UI Coordinator
//
// When the MoE generates complex UI updates (e.g. streaming a markdown response
// while also sending JSON commands to build widgets), this Dart module parses
// the mixed-modal stream and coordinates the Flutter widget tree updates.

import 'dart:convert';

class MoeUiCoordinator {
  MoeUiCoordinator() {
    print("[Dart UI] Initialized Flutter MoE UI Coordinator.");
  }

  /// Parses an incoming SSE stream chunk from the MoE.
  /// The stream may contain markdown text, or special `[WIDGET: ...]` tags
  /// that instruct Flutter to render native UI components dynamically.
  void processStreamChunk(String chunk, Function(String) onTextUpdate, Function(Map<String, dynamic>) onWidgetCommand) {
    // Check for Widget insertion commands generated by Expert #8 (UI Gen)
    final widgetRegex = RegExp(r'\[WIDGET: (\{.*?\})\]');
    
    if (widgetRegex.hasMatch(chunk)) {
      final match = widgetRegex.firstMatch(chunk);
      if (match != null && match.groupCount >= 1) {
        try {
          final jsonString = match.group(1)!;
          final widgetCommand = jsonDecode(jsonString);
          onWidgetCommand(widgetCommand);
          
          // Strip the command from the visible text
          final cleanText = chunk.replaceAll(widgetRegex, '');
          if (cleanText.trim().isNotEmpty) {
            onTextUpdate(cleanText);
          }
        } catch (e) {
          print("[Dart UI] Failed to parse Widget JSON: $e");
          onTextUpdate(chunk); // Fallback to raw text
        }
      }
    } else {
      // Normal markdown text streaming
      onTextUpdate(chunk);
    }
  }

  // Example widget builder invoked by the coordinator
  // Widget buildDynamicWidget(Map<String, dynamic> command) {
  //   switch(command['type']) {
  //     case 'button':
  //       return ElevatedButton(onPressed: () {}, child: Text(command['label']));
  //     default:
  //       return SizedBox.shrink();
  //   }
  // }
}
