import subprocess
import os
import tempfile
from typing import Tuple, Optional

# OMNI OPEN INTERPRETER: Code Executor
# Python domain logic for safely executing dynamically generated code snippets from LLMs.
# Source: OpenInterpreter/open-interpreter

class ExecutionError(Exception):
    pass

class CodeExecutor:
    """
    Executes Python or shell code generated by an LLM in a controlled subprocess environment.
    """
    def __init__(self, timeout_sec: int = 30):
        self.timeout_sec = timeout_sec

    def execute_python(self, code: str) -> Tuple[Optional[str], Optional[ExecutionError]]:
        """
        Executes python code by writing to a temporary file and running it.
        Uses monadic error handling return types.
        """
        try:
            with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as temp_script:
                temp_script.write(code)
                temp_path = temp_script.name

            # Run via subprocess
            result = subprocess.run(
                ['python3', temp_path],
                capture_output=True,
                text=True,
                timeout=self.timeout_sec
            )

            os.remove(temp_path)

            if result.returncode != 0:
                return None, ExecutionError(f"Execution failed (Exit {result.returncode}):\n{result.stderr}")

            return result.stdout, None

        except subprocess.TimeoutExpired:
            return None, ExecutionError(f"Execution timed out after {self.timeout_sec} seconds.")
        except Exception as e:
            return None, ExecutionError(f"System error during execution: {str(e)}")

    def execute_bash(self, command: str) -> Tuple[Optional[str], Optional[ExecutionError]]:
        """
        Executes a bash command.
        """
        try:
            result = subprocess.run(
                command,
                shell=True,
                executable='/bin/bash',
                capture_output=True,
                text=True,
                timeout=self.timeout_sec
            )

            if result.returncode != 0:
                return None, ExecutionError(f"Bash execution failed (Exit {result.returncode}):\n{result.stderr}")

            return result.stdout, None

        except subprocess.TimeoutExpired:
            return None, ExecutionError(f"Bash execution timed out after {self.timeout_sec} seconds.")
        except Exception as e:
            return None, ExecutionError(f"System error during bash execution: {str(e)}")
