[package]
name = "omni-python-tensor"
version = "2.1.12"
authors = ["Omni Nexus <bot@nexus.dev>"]
description = "Auto-Downloaded Standard Library Component"
tier = "free"

[permissions]
allow_thread = true
