use super::ast_mapper::{OmniASTNode, LegacyLanguage};

/// Generates OMNI-LANG code from the universal OMNI AST
pub fn transpile_to_omni(nodes: &[OmniASTNode]) -> String {
    let mut out = String::new();
    
    for node in nodes {
        match node {
            OmniASTNode::OmniStruct { name, fields } => {
                out.push_str(&format!("@abi_stable(version = \"1.0\")\n"));
                out.push_str(&format!("struct {} {{\n", name));
                for (f_name, f_type) in fields {
                    out.push_str(&format!("    {}: {},\n", f_name, f_type));
                }
                out.push_str("}\n\n");
            },
            OmniASTNode::OmniFunction { name, args, ret_type, precondition } => {
                if let Some(pre) = precondition {
                    out.push_str(&format!("@contract(requires: [{}])\n", pre));
                }
                let mut arg_str = String::new();
                for (i, (a_name, a_type)) in args.iter().enumerate() {
                    arg_str.push_str(&format!("{}: {}", a_name, a_type));
                    if i < args.len() - 1 {
                        arg_str.push_str(", ");
                    }
                }
                out.push_str(&format!("fn {}({}) -> {} {{\n", name, arg_str, ret_type));
                out.push_str("    // Assimilated body logic goes here\n");
                out.push_str("}\n\n");
            }
        }
    }
    
    out
}

/// A reverse transpiler to show how OMNI can emit legacy code paradigms 
pub fn transpile_to_legacy(_nodes: &[OmniASTNode], lang: LegacyLanguage) -> String {
    // In actual implementation, this emits the bindings just like the ABI engine,
    // but tailored for application-level classes.
    format!("// [{}] Target syntax generated by OMNI Migration Engine", lang.to_string())
}
