[package]
name = "omni-module-157"
version = "2.1.157"
authors = ["Omni Nexus <bot@nexus.dev>"]
description = "Auto-Downloaded Standard Library Component"
tier = "free"

[permissions]
allow_thread = true
