# OMNI Compute Layer - CoML Assistant
import ast

class CoMLError(Exception):
    pass

class Result:
    def __init__(self, value=None, error=None):
        self.value = value
        self.error = error
        
    def is_ok(self):
        return self.error is None

def validate_python_snippet(code: str) -> Result:
    """
    Validates machine learning code snippets generated by LLM.
    """
    try:
        if not code.strip():
            return Result(error=CoMLError("Empty code snippet"))
            
        # Parse AST to ensure syntax validity
        parsed = ast.parse(code)
        
        # Analyze imports specifically for ML libraries
        imports = [node.names[0].name for node in ast.walk(parsed) if isinstance(node, ast.Import)]
        
        return Result(value={"valid": True, "detected_imports": imports})
    except SyntaxError as e:
        return Result(error=CoMLError(f"Syntax error in snippet: {str(e)}"))
    except Exception as e:
        return Result(error=CoMLError(f"Validation failed: {str(e)}"))
