// omni_vector_store.go — Vector Database Wrapper
// Layer: Domain / Go
//
// In-memory or Redis-backed vector store wrapper for storing and querying
// document embeddings generated by OMNI's RAG and NLP pipelines.

package search

import (
	"context"
	"errors"
	"math"
	"sort"
	"sync"
)

type VectorRecord struct {
	ID        string
	Embedding []float32
	Metadata  map[string]string
}

type SearchResult struct {
	Record          VectorRecord
	SimilarityScore float32
}

type OmniVectorStore struct {
	mu      sync.RWMutex
	records []VectorRecord
}

func NewOmniVectorStore() *OmniVectorStore {
	return &OmniVectorStore{
		records: make([]VectorRecord, 0),
	}
}

func (s *OmniVectorStore) Upsert(ctx context.Context, records []VectorRecord) error {
	s.mu.Lock()
	defer s.mu.Lock()

	// In a real system, this indexes into an HNSW graph or pushes to PgVector.
	// For this domain abstraction, we append to a slice.
	s.records = append(s.records, records...)
	return nil
}

func (s *OmniVectorStore) Search(ctx context.Context, queryVector []float32, topK int) ([]SearchResult, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if len(s.records) == 0 {
		return nil, errors.New("vector store is empty")
	}

	var results []SearchResult

	// Brute-force cosine similarity for domain mock
	for _, record := range s.records {
		if len(record.Embedding) != len(queryVector) {
			continue
		}

		score := cosineSimilarity(queryVector, record.Embedding)
		results = append(results, SearchResult{
			Record:          record,
			SimilarityScore: score,
		})
	}

	// Sort by highest similarity
	sort.Slice(results, func(i, j int) bool {
		return results[i].SimilarityScore > results[j].SimilarityScore
	})

	if len(results) > topK {
		results = results[:topK]
	}

	return results, nil
}

func cosineSimilarity(a, b []float32) float32 {
	var dotProduct, normA, normB float32
	for i := 0; i < len(a); i++ {
		dotProduct += a[i] * b[i]
		normA += a[i] * a[i]
		normB += b[i] * b[i]
	}

	if normA == 0 || normB == 0 {
		return 0
	}

	return dotProduct / (float32(math.Sqrt(float64(normA))) * float32(math.Sqrt(float64(normB))))
}
