import React, { useState, useEffect } from 'react';

// OMNI INTERFACE LAYER: Tagging Studio
// UI for reviewing, editing, and confirming tags generated by the ML pipeline.

interface ImageTags {
  id: string;
  url: string;
  tags: string[];
}

export const TaggingStudio: React.FC = () => {
  const [currentImage, setCurrentImage] = useState<ImageTags | null>(null);
  const [editableTags, setEditableTags] = useState<string[]>([]);
  const [newTag, setNewTag] = useState('');

  useEffect(() => {
    // Zero-Mock fetch from Omni backend
    fetch('/api/omni/imagetagging/next')
      .then(res => res.json())
      .then(data => {
        if (data.status === 'Ok') {
          setCurrentImage(data.payload);
          setEditableTags(data.payload.tags);
        }
      });
  }, []);

  const handleAddTag = () => {
    if (newTag && !editableTags.includes(newTag)) {
      setEditableTags([...editableTags, newTag.toLowerCase()]);
      setNewTag('');
    }
  };

  const handleRemoveTag = (tagToRemove: string) => {
    setEditableTags(editableTags.filter(t => t !== tagToRemove));
  };

  const handleSave = () => {
    // Commit changes to Omni
    console.log("Saving tags for", currentImage?.id, editableTags);
    // Fetch next image...
  };

  if (!currentImage) return <div className="p-8 text-white font-mono">Loading Neural Tagger...</div>;

  return (
    <div className="p-8 bg-gray-900 min-h-screen text-white font-sans flex gap-8">
      <div className="flex-1 bg-black border border-gray-800 rounded-lg p-4 flex items-center justify-center shadow-xl">
        <img src={currentImage.url} alt="To be tagged" className="max-w-full max-h-[80vh] object-contain" />
      </div>
      
      <div className="w-96 flex flex-col">
        <h1 className="text-2xl font-bold mb-4 text-purple-400 border-b border-gray-800 pb-2">Omni Tag Studio</h1>
        
        <div className="flex flex-wrap gap-2 mb-6 max-h-[50vh] overflow-y-auto content-start">
          {editableTags.map(tag => (
            <span key={tag} className="bg-purple-900/50 text-purple-200 px-3 py-1 rounded-full text-sm flex items-center gap-2 border border-purple-800">
              {tag}
              <button onClick={() => handleRemoveTag(tag)} className="text-purple-400 hover:text-white">&times;</button>
            </span>
          ))}
        </div>

        <div className="mt-auto">
          <div className="flex gap-2 mb-4">
            <input 
              type="text" 
              value={newTag} 
              onChange={e => setNewTag(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleAddTag()}
              className="bg-gray-800 border border-gray-700 rounded px-3 py-2 flex-1 outline-none focus:border-purple-500"
              placeholder="Add new tag..."
            />
            <button onClick={handleAddTag} className="bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded transition">Add</button>
          </div>
          
          <button onClick={handleSave} className="w-full bg-purple-600 hover:bg-purple-500 text-white font-bold py-3 rounded shadow-lg transition-transform active:scale-95">
            Confirm & Next
          </button>
        </div>
      </div>
    </div>
  );
};
