package omni.llm.rl

# OMNI LLM-RL: Reward Guard Policy
# Validates that reward scores generated by RM (Reward Models) fall within safe operational boundaries.
# Source: changyeyu/LLM-RL-Visualized

default is_valid_reward = false

# A reward is valid if it sits within the [-10.0, 10.0] numerical bounds
# and the origin model signature is authorized.
is_valid_reward {
    input.reward_score >= -10.0
    input.reward_score <= 10.0
    valid_reward_model(input.model_signature)
}

valid_reward_model(signature) {
    # Assume data.authorized_rms is injected by OPA controller
    data.authorized_rms[_] == signature
}

# Explicit deny if reward indicates severe misalignment (extreme negative anomaly)
deny[msg] {
    input.reward_score < -20.0
    msg := "Catastrophic reward score detected, halting RLHF trajectory."
}

# Explicit deny if reward indicates potential reward hacking (extreme positive anomaly)
deny[msg] {
    input.reward_score > 20.0
    msg := "Unusually high reward score detected, possible reward hacking."
}
