[package]
name = "omni-module-186"
version = "2.1.186"
authors = ["Omni Nexus <bot@nexus.dev>"]
description = "Auto-Downloaded Standard Library Component"
tier = "free"

[permissions]
allow_thread = true
