[package]
name = "omni-webrtc"
version = "2.0.0-enterprise"
authors = ["ANTIGRAVITY <omni@architecture.dev>"]
edition = "omni-2025"

[dependencies]
omni-std = "^2.0"
omni-net-tcp = "^1.0"
omni-crypto-hash = "^1.0"

[dev-dependencies]
omni-test = "^1.0"

[permissions]
allow_net = ["0.0.0.0/0"]
allow_memory = true
allow_thread = true