# ============================================================
# Omnifile.toml â€” OMNI Framework Project
# ============================================================

[package]
name        = "myapp"
version     = "1.0.0"
edition     = "omni-2025"
authors     = []
description = ""
license     = "MIT"

[dependencies]
omni-std    = "1.0.0"

[dev-dependencies]
omni-test   = "1.0.0"
omni-log    = "1.0.0"

[scripts]
dev     = "omni serve --hot-reload"
build   = "omni build --release"
test    = "omni test --all --coverage"

[permissions]
allow_net    = []
allow_fs     = ["./data/"]
allow_env    = []
allow_thread = true

[build]
target      = ["x86_64-windows"]
optimize    = "debug"
entry_point = "src/main.omni"