/* OMNI Data & Analytics Layer
   SAS Script for Advanced Statistical Processing
   Reads output telemetry from the Omni Universal Binary to model training loss curves 
   and predict convergence times using ARIMA models.
*/

OPTIONS NONOTES NOSTIMER NOSOURCE NOSYNTAXCHECK;

/* 1. Import training metrics generated by the Omni Engine */
FILENAME omnilogs '/mnt/data/omni_training_loss.csv';

PROC IMPORT DATAFILE=omnilogs
    OUT=WORK.OmniMetrics
    DBMS=CSV
    REPLACE;
    GETNAMES=YES;
RUN;

/* 2. Basic Descriptive Statistics of the Training Epochs */
PROC MEANS DATA=WORK.OmniMetrics N MEAN STD MIN MAX;
    VAR Epoch Loss LearningRate;
    TITLE "OMNI Statistical Summary of Training Run";
RUN;

/* 3. Fit an ARIMA model to forecast the loss curve convergence */
/* We aim to predict when Loss drops below 0.001 */
PROC ARIMA DATA=WORK.OmniMetrics;
    IDENTIFY VAR=Loss;
    ESTIMATE P=1 Q=1;
    FORECAST LEAD=50 OUT=WORK.OmniForecast;
RUN;

/* 4. Output results to a printable HTML report */
ODS HTML FILE='/mnt/data/omni_convergence_report.html';

PROC SGPLOT DATA=WORK.OmniForecast;
    SERIES X=Epoch Y=Loss / LINEATTRS=(COLOR=Blue THICKNESS=2) LEGENDLABEL="Actual Loss";
    SERIES X=Epoch Y=FORECAST / LINEATTRS=(COLOR=Red PATTERN=Dash THICKNESS=2) LEGENDLABEL="Predicted Loss";
    TITLE "OMNI Transformer Training Loss Convergence Prediction";
    XAXIS LABEL="Epoch";
    YAXIS LABEL="Categorical Cross-Entropy Loss";
RUN;

ODS HTML CLOSE;

OPTIONS NOTES STIMER SOURCE SYNTAXCHECK;
