// ==========================================
// 🛣️ AUTO-GENERATED BY OMNI-ROUTER — DO NOT EDIT!
// Regenerated setiap kali 'omni dev' atau 'omni build' dijalankan.
// Source: api/routes/auto/*.go
// Timestamp: 2026-04-03T20:11:18.938Z
// ==========================================
//
// 🌐 OMNI-VERB PROTOCOL:
// Setiap handler di api/routes/auto/ menggunakan RESTful Matrix Switch:
//   GET     → Baca data
//   POST    → Buat data baru
//   PUT     → Perbarui semua field
//   PATCH   → Perbarui sebagian field
//   DELETE  → Hapus data
//   OPTIONS → Ditangani otomatis oleh God Middleware (CORS Preflight)
//
// Scaffold baru: omni make route <nama>
// ==========================================
package routes

import (
	"net/http"
)

// RegisterAutoRoutes mendaftarkan semua file-based API routes
// File sumber: api/routes/auto/*.go
func RegisterAutoRoutes(mux *http.ServeMux) {
	// Belum ada auto-route. Jalankan: omni make route <nama>
	_ = mux
}
